In [1]:
import numpy as np

In [17]:
# Create a null vector / 1D array of size 10 and update fifth index to 11.

a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a[5] =11

print(a)

[ 1  2  3  4  5 11  7  8  9 10]


In [18]:
# Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c = b.reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
# Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
d[1:-1, 1:-1] = 0
d

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [46]:
# Take a look at the following matrix. Access the [2, 1,1]

z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [47]:
z[2, 1,1]

2

In [71]:
# Assignment

# Create a 4x4 matrix with values ranging from 0 to 3.

x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
x += np.arange(4)
x

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [90]:
# Create and array with shape of 4x4 and turn it into two arrays along the second axis.

t = np.arange(16).reshape(4,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
t = np.hsplit(x, [2,6])
t

[array([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]),
 array([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]]),
 array([], shape=(4, 0), dtype=float64)]